### ISSUE TITLE
内核占用CPU高

### ISSUE THREAD

**Issue by liuchao1899** [clash-verge-rev/clash-verge-rev.github.io#4]
win10系统，电脑在使用一段时间,或是静置一段时间后（差不多半个小时）clash-meta.exe会莫名的占用CPU变高导至电脑CPU风扇高转，试过多个版本，只要换回1.18.1内核后问题消失。

**Comment by dongchengjie** [comment]
这特么是文档issue，你都知道了是内核问题你不去内核发issue

**Comment by liuchao1899** [comment]
不好意思我发错了,但是想删除时好像没有找到删除的地方.




                       
原始邮件
                       
                     

发件人："dongchengjie"< ***@***.*** &gt;;

发件时间：2024/5/9 16:39

收件人："clash-verge-rev/clash-verge-rev.github.io"< ***@***.*** &gt;;

抄送人："liuchao1899"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [clash-verge-rev/clash-verge-rev.github.io] 内核占用CPU高 (Issue #4)




 
这特么是文档issue，你都知道了是内核问题你不去内核发issue
