### ISSUE TITLE
非静默启动下，TUN 模式在软件重启后将遗忘节点

### ISSUE THREAD

**Issue by Corbyn-Kyle** [clash-verge-rev/clash-verge-rev.github.io#7]
基础测试，在 windows 版本 1.7.7 中，只使用TUN模式不开启系统代理。

非静默启动，在手动关闭软件后，重新打开，软件将遗忘最近链接的节点并自动切换为直连模式（规则/全局的设定不受影响）；

开启静默启动后，手动关闭软件并重启，软件可正常继承最近链接的节点。

该 BUG 是于尝试过静默启动之后发现，暂不了解对于新下载的用户，不进行默认设置的修改是否能实现 BUG 的复现。

![Screenshot](https://github.com/user-attachments/assets/afd46ed8-3603-4bba-87b5-60e09b2bd53f)

**Comment by Corbyn-Kyle** [comment]
后续测试，该现象应为显示 BUG，关闭静默启动所弹出的初始窗口虽显示直连（该显示不会主动切换），但于刷新窗口页面后，可恢复显示正确的链接状态（由直连转为最近链接的节点），期间流量转发依旧正常。

该发表先前并未添加 bug 标签，如项目维护者关注，劳烦进行一下标签的补充，非常感谢！

**Comment by wonfen** [comment]
这里是文档，请到项目下发issue
